# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

use_frameworks!

target 'Thinh' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  

  # Firebase
  pod 'JSQMessagesViewController'
  pod 'AFNetworking'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  pod 'FacebookCore'
  pod 'FacebookLogin'
  pod 'FacebookShare'
  pod 'FBSDKCoreKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKLoginKit'
  
  pod 'Gloss'
  pod 'RxSwift'
  pod 'RxCocoa'

  pod 'NSDate+TimeAgo'
end
